### ISSUE TITLE
New Relic Java instructions for Using an Existing New Relic License Key unclear

### ISSUE THREAD

**Issue by cobyrne-pivot** [pivotal-cf/docs-pws-services#30]
I can't tell what I should do to connect my app to my existing New Relic account from reading this section of the docs

https://github.com/pivotal-cf/docs-pws-services/blob/master/services/newrelic/index.html.md.erb#L150

**Comment by pspinrad** [comment]
@cobyrne-pivot Thank you for raising this issue, and I'm sorry that you are having trouble. Please sign in to [Pivotal Support](https://support.pivotal.io) and consult the community or open a case. See [Pivotal Support for Subscribers](https://content.pivotal.io/support/pivotal-support-for-subscribers) for how to do this.
If Pivotal Support's investigation determines that this is a general problem, rather than an issue that is fairly specific to your situation, we will update the documentation.

**Comment by cobyrne-pivot** [comment]
Hi @pspinrad ,

My issue isn't a support issue but is indeed a docs issue: the docs don't explain how to go about setting up a Java app on CF to use an existing New Relic license. We figured out how to make this work by looking at other apps my team maintains. I'm also in SF and would be happy to pair with someone to explain how we got it working so that the docs can be improved.

**Comment by pspinrad** [comment]
@cobyrne-pivot yeah-- I almost didn't send the contact-support boilerplate because it did sound more docs-y, am glad you're following up.  I asked a couple of folks about this, but no answers so far.  Yes, let's pair, if you're in the Pivotal SF office, I'm southwest corner of 4th floor or @pspinrad on Slack.
